id: I7B4B9E98
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:11:32+00:00'
last_modified: '2022-06-08T09:39:54.405959+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1870
  title: འཇམ་དབྱངས་དཀོན་མཆོག་བཟང་པོའི་རྣམ་ཐར་དད་པའི་ལྗོན་ཤིང་རྒྱས་བྱེད་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    254F:
      image_group_id: I1CZ1947
      title: Volume 1 of 'jam dbyangs dkon mchog bzang po'i rnam thar dad pa'i ljon
        shing rgyas byed
      total_pages: 172
      order: 1
      base_file: 254F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
