id: P006972
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ1870
  title: འཇམ་དབྱངས་དཀོན་མཆོག་བཟང་པོའི་རྣམ་ཐར་དད་པའི་ལྗོན་ཤིང་རྒྱས་བྱེད་
  author: ''
  volumes:
    431f4fb6ea354dbca27ba2deceaa2600:
      image_group_id: I1CZ1947
      title: Volume 1 of 'jam dbyangs dkon mchog bzang po'i rnam thar dad pa'i ljon
        shing rgyas byed
      volume_number: 1
      total_pages: 172
      base_file: v001.txt
