id: P006972
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1870
  title: འཇམ་དབྱངས་དཀོན་མཆོག་བཟང་པོའི་རྣམ་ཐར་དད་པའི་ལྗོན་ཤིང་རྒྱས་བྱེད་
  author: ''
  volumes:
    4824de2636eb42688f82be846f635ebb:
      image_group_id: I1CZ1947
      title: ''
      volume_number: 1
      total_pages: 172
ebook_metadata:
  title: འཇམ་དབྱངས་དཀོན་མཆོག་བཟང་པོའི་རྣམ་ཐར་དད་པའི་ལྗོན་ཤིང་རྒྱས་བྱེད་
  author: ''
  sku: P006972
  cover: cover.jpg
  layers:
  - pagination
